# Site
name: "Blogissm"
title: "Blogissm"
description: "Viewing the world through the lens of a blog!"
logo: 'assets/images/blogissm_logo.png'
favicon: 'assets/images/blogissm_logo.png'
baseurl: /blogissm
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: swastishreya13@gmail.com

# Authors
authors:
  swasti:
    name: Swasti
    display_name: SSM    
    avatar: 'assets/images/avatar-swasti.jpg'
    email: swastishreya13@gmail.com
    web: https://swastishreya.github.io
    twitter: https://x.com/SwastiShreya
    description: "Author of Blogissm, i.e. SSM's right brain (for all practical purposes). For left brain, please refer to her resume."
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/avatar-sal.png'
    email: swastishreya13@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. They are the reason why it was so easy for SSM to write her blogs."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
